config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  post 'sessions/new'
  delete 'sessions/destroy'

  resources :teachers

  resources :parents

end

app/models/parent.rb
class Parent < ActiveRecord::Base
  belongs_to :teacher
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }

  # Returns the hash digest of the given string.
  def digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController
  def new
    @parent = parent.new
  end

  def create
    @parent = parent.new(parent_params)
    if @parent.save
      redirect_to parents_path, notice: 'parent was successfully created.'
    else
      render :new
    end
  end

  def show
    redirect_to parents_path
  end

  def edit
    @categories = Category.all
    @parents = parent.all
  end

  def update
    if @parent.update(parent_params)
      redirect_to @parent, notice: 'parent was successfully updated.'
    else
      render :edit
    end
  end

  def index
    @parents = Parent.all
  end

  def destroy
    @parent = parent.find(params[:id])
    @parent.destroy
    respond_to do |format|
      format.html { redirect_to parents_path, notice: 'parent was successfully destroyed.' }
    end
  end

  private
  def set_parent
    @parent = parent.find(params[:id])
  end

  # def set_meal
  #   session[:parent] = parent.find(params[:id]).name
  # end
  #
  # def categories
  #   @categories = Category.all
  # end

  def parent_params
    params.require(:parent).permit(:name, :price, :category_id, :meal_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @teacher = Teacher.find_by(email: params[:session][:email].downcase)
    if @teacher && teacher.authenticate(params[:session][:password])
      log_in @teacher
      redirect_to @teacher
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController

  def new
  @teacher = Teacher.new
end

def create
  @teacher = Teacher.new(teacher_params)
  if @teacher.save
    log_in @teacher
    flash[:success] = "Welcome to the Sample App!"
    redirect_to @teacher, notice: 'teacher was successfully created.'
  else
    render :new
  end
end

def show
  @teacher = Teacher.find(params[:id])
  @parents = Parent.where(teacher_id: @teacher.id)
end

def edit
  @teachers = Teacher.all
end

def update
  if @teacher.update(teacher_params)
    redirect_to @teacher, notice: 'teacher was successfully updated.'
  else
    render :edit
  end
end

def index
  # @entree_teachers = teacher.all.where(category_id: 1)
  # @app_teachers = teacher.all.where(category_id: 2)
  # @special_teachers = teacher.all.where(category_id: 3)
  @categories = Category.all
  @meals = Meal.all
end

def destroy
  @teacher = Teacher.find(params[:id])
  @teacher.destroy
  respond_to do |format|
    format.html { redirect_to sessions_new_path, notice: 'teacher was successfully destroyed.' }
  end
end

private
def set_teacher
  @teacher = Teacher.find(params[:id])
end
#
# def set_meal
#   session[:teacher] = teacher.find(params[:id]).name
# end
# #
# def categories
#   @categories = Category.all
# end

def teacher_params
  params.require(:teacher).permit(:name, :email, :password)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(teacher)
  session[:teacher_id] = teacher.id
  end

  def current_user
  @current_user ||= Teacher.find_by(id: session[:id])
  end

  def log_out
    session.delete(:teacher_id)
    @current_user = nil
  end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TeacherApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/parents/show.html.erb
<h1>Parents#show</h1>
<p>Find me in app/views/parents/show.html.erb</p>

app/views/teachers/_form.html.erb
<%= form_for(@teacher) do |f| %>
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% @teacher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="new">
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>

    <div class="field>">
      <%= f.label :password, 'Password' %><br>
      <%= f.password_field :password%>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  </div>

<% end %>

app/views/teachers/new.html.erb
<h1>New Teacher</h1>

<%= render 'form' %>

<%= link_to 'Back', sessions_new_path %>

app/views/teachers/show.html.erb
<% @parents.each do |parent| %>
  <div class="category">
    <h2><%= parent.parent_name %></h2>
    <table>
      <thead>
        <tr>

          <th>Item</th>
          <th>Price</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <tr>
          <td><%= link_to "#{parent.parent_name}", edit_parent_path(parent) %></td>
          <td><%= parent.parent_email %></td>
          <td><%= parent.student_name %></td>
        </tr>
      </tbody>
    </table>
  </div>
<% end %>